// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgNxRnXSup7DS_-G9FWLac1MbMeEYbAPo',
    appId: '1:941226019975:web:25eb0c6357e85b9a067c22',
    messagingSenderId: '941226019975',
    projectId: 'notes-f5e39',
    authDomain: 'notes-f5e39.firebaseapp.com',
    storageBucket: 'notes-f5e39.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCq8QJx-uyS-o3eqDCv75PzYprVp2X-TGQ',
    appId: '1:941226019975:android:cd3c0feb7275e750067c22',
    messagingSenderId: '941226019975',
    projectId: 'notes-f5e39',
    storageBucket: 'notes-f5e39.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPgOrGOmzdFczOaCuiJVUxm9I0KUr6MwE',
    appId: '1:941226019975:ios:be696a9bbc53802a067c22',
    messagingSenderId: '941226019975',
    projectId: 'notes-f5e39',
    storageBucket: 'notes-f5e39.appspot.com',
    iosClientId: '941226019975-404rug3ct7eirm5ispnjaqd7homvq657.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterNotesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPgOrGOmzdFczOaCuiJVUxm9I0KUr6MwE',
    appId: '1:941226019975:ios:18f42233941e0200067c22',
    messagingSenderId: '941226019975',
    projectId: 'notes-f5e39',
    storageBucket: 'notes-f5e39.appspot.com',
    iosClientId: '941226019975-f4hu7inptkq98oq7el52823f49gdnrs6.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterNotesApp.RunnerTests',
  );
}
